<Project Sdk="Microsoft.NET.Sdk">
  <!-- Common properties -->
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <!-- macOS specific properties -->
  <PropertyGroup Condition="!$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net9.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>
    <ApplicationId>com.yourcompany.avaloniaapp</ApplicationId>
  </PropertyGroup>

  <!-- Windows specific properties -->
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.4" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.4" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.4">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.2.0-beta.4" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="FlaUI.Core" Version="5.0.0" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="FlaUI.UIA3" Version="5.0.0" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Whisper.net" Version="1.8.1" />
    <PackageReference Include="Whisper.net.Runtime" Version="1.8.1" />
  </ItemGroup>
</Project>
